### ISSUE TITLE
Mpeg-DASH support

### ISSUE THREAD

**Issue by Palethorn** [gramk/chrome-hls#7]
Hello,
I liked your extension, and figured it lacks Mpeg-DASH support also. Since this is an open source project I took the liberty of forking your project and adding the necessary changes myself. I also added Widevine DRM support. Changes are here: https://github.com/Palethorn/chrome-hls/commits/master. If you wish, I can create a pull request. If not, and you want this extension to remain pure HLS, no harm done.

**Comment by ghouet** [comment]
Hi there,

Considering the name I chose and to make it easier to maintain, I think it makes sense to keep them separate. Feel free to use the logic from this extension and publish a dash version in the webstore.

Thanks for offering though!

**Comment by Palethorn** [comment]
Thank you. No problem, I'll maintain a fork then.
