### ISSUE TITLE
Firefox 58 update breaks hls.js

### ISSUE THREAD

**Issue by Palethorn** [gramk/chrome-hls#9]
Check my commit https://github.com/Palethorn/chrome-native-dash-hls/commit/b4eec513ff434b5393f0326bc09ea2cf3965c699

**Comment by ghouet** [comment]
Done, thanks a lot!

**Comment by Palethorn** [comment]
They rejected my submission with this fix. Reasoning:
"The use of 'blob' is not allowed in the manifest.json's CSP as it can cause major security issues."
I'll try and get some more information.

**Comment by ghouet** [comment]
My submission was approved just fine, I just added it as an update. Although it may be removed later since the review is not instantaneous apparently.

**Comment by Palethorn** [comment]
Mine was approved, then rejected after a while, and made unavailable on the gallery. I made a ticket on hls.js project to see if I can somehow circumvent this https://github.com/video-dev/hls.js/issues/1562. They also reported bad sha256 hash on the jquery lib. Just a heads up.

**Comment by Palethorn** [comment]
When I initialize the player like this 'blob:' is needed no more
```
var hls = new Hls({
        enableWorker: false
    });
```
